# Generated by Django 4.2.14 on 2024-07-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_alter_cook_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cook',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
