# Generated by Django 4.2.14 on 2024-07-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_alter_dishtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishtype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
